### ISSUE TITLE
HY2节点转换clash时，如果密码带有"/"，则出现bug

### ISSUE THREAD

**Issue by TaoRone** [jaaksii/sublink#17]
经过反复测试：
**当hy2的密码中带有"/"符号时，必然转换错误**
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**更新：
经测试，转换为v2ray时，虽然服务器不报错，但实测该转换同样不能生效，尚未测试其他协议如果密码包含该符号是否生效
目前我自己已经把密码修改了，但此bug建议调整一下**

报错如下：
```
[2024-04-14 23:04:13,870] ERROR in app: Exception on /sub/clash/aHky [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app/view.py", line 611, in get_sub_url
    data = clash_encode(subs)
  File "/app/app/view.py", line 494, in clash_encode
    clash()
  File "/app/app/view.py", line 480, in clash
    proxy = node_parse.hysteria2()
  File "/app/app/view.py", line 397, in hysteria2
    server = if_ipv6_address(urlpath.split('@')[1].rsplit(':', 1)[0])
IndexError: list index out of range
```

**Comment by hktkjj** [comment]
当有订阅失效，也是提示这个错误
