### ISSUE TITLE
clash订阅报错

### ISSUE THREAD

**Issue by rainsum2022** [jaaksii/sublink#18]
## 复现方式

添加如下一条测试订阅

```bash
vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICLjgJDmtYXor63jgJFtbzBzaDl5MiIsCiAgImFkZCI6ICIxMjcuMC4wLjEiLAogICJwb3J0IjogMTc0NjgsCiAgImlkIjogImQxYTMzMDBhLWJkNzMtNDAwYi1iMzVmLTgzMDkxNzY5MWZjYyIsCiAgIm5ldCI6ICJ0Y3AiLAogICJ0eXBlIjogImh0dHAiLAogICJ0bHMiOiAibm9uZSIsCiAgInBhdGgiOiAiLzdkZjRmNTJiIiwKICAiaG9zdCI6ICJ3d3cuYmluZy5jb20iCn0=|TEST
```
## 错误日志

```plantext
sublink    | [2024-04-28 12:59:44,265] ERROR in app: Exception on /sub/clash/5rWF6K+t [GET]
sublink    | Traceback (most recent call last):
sublink    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
sublink    |     response = self.full_dispatch_request()
sublink    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
sublink    |     rv = self.handle_user_exception(e)
sublink    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
sublink    |     rv = self.dispatch_request()
sublink    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
sublink    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
sublink    |   File "/app/app/view.py", line 611, in get_sub_url
sublink    |     data = clash_encode(subs)
sublink    |   File "/app/app/view.py", line 494, in clash_encode
sublink    |     clash()
sublink    |   File "/app/app/view.py", line 450, in clash
sublink    |     proxy = node_parse.vmess()
sublink    |   File "/app/app/view.py", line 193, in vmess
sublink    |     aid = int(proxy.get('aid'))
sublink    | TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by nickdlkk** [comment]
同样问题 应该是订阅里面缺少alterId

**Comment by rainsum2022** [comment]
> 同样问题 应该是订阅里面缺少alterId

对，我用3xui创建的订阅确实没这个东西，已经自己处理了。感觉这种处理不了的应该直接忽略掉这一条数据给出日志提示，而不是报错影响整个功能的使用。
